user/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin

db = SQLAlchemy()

class User(UserMixin,db.Model):
    __tablename__ = "user"
    id = db.Column(db.Integer,primary_key=True,nullable=False)
    username = db.Column(db.String(64),unique=True,nullable=False)
    password = db.Column(db.String(128),nullable=False)
    icon = db.Column(db.String(500),nullable=True)
    # ablout_me
    about_me = db.Column(db.String(150),nullable=True)
    # 建立反向引用
    comments = db.relationship('Comment',backref='user')

    def __str__(self):
        return self.username

    def to_dict(self):
        return dict(id=self.id,
                    username=self.username,
                    icon=self.icon,
                    about_me=self.about_me,
                    comments=[comment.to_dict()for comment in self.comments])

class Comment(db.Model):
    __tablename__ = "comment"
    id = db.Column(db.Integer,primary_key=True)
    # 评论内容
    content = db.Column(db.String(500))
    # 外键关联
    user_id = db.Column(db.Integer,db.ForeignKey("user.id"))
    article_id = db.Column(db.Integer,db.ForeignKey("article.id"))

    def to_dict(self):
        return dict(id=self.id,
                    content=self.content,
                    user_id=self.user_id,
                    article_id=self.article_id)

# 多对多关系
ships = db.Table("ships",
    db.Column('user.id',db.Integer,db.ForeignKey("user.id")),
    db.Column('article.id',db.Integer,db.ForeignKey("article.id")))

class Article(db.Model):
    __tablename__ = "article"
    id = db.Column(db.Integer,primary_key=True)
    # 文章标题
    titile = db.Column(db.String(500),nullable=False)
    # 内容
    content = db.Column(db.String(5000),nullable=False)
    user_id = db.Column(db.Integer,db.ForeignKey("user.id"))

    users = db.relationship("User",secondary=ships,backref=
    db.backref("articles",lazy="dynamic"))
    # 反向应用
    comments = db.relationship("Comment",backref="article")

    def to_dict(self):
        return dict(id=self.id,
                    title=self.titile,
                    content=self.content,
                    user_id=self.user_id,
                    comments=[comment.to_dict()for comment in self.comments])

comment/views.py
import json
from flask import Blueprint,request,render_template,jsonify
from user.models import db, Article,Comment
from common_function import after_login

article = Blueprint("article",__name__)

@article.route("/write/",methods=["GET","POST"])
@after_login
def write():
    if request.method == "GET":
        return render_template("article/write.html")
    elif request.method == "POST":
        data = json.loads(request.data.decode())
        user_id = data.get("user_id")
        title = data.get("title")
        content = data.get("content")
        if user_id == "":
            warn = "您还没有登录，请登录后再发表！"
        article = Article(titile=title,content=content,user_id=user_id)
        # 提交到数据库
        db.session.add(article)
        db.session.commit()
        return jsonify("发表成功！")

@article.route("/<pk>/",methods=["GET","POST"])
def show(pk):
    if request.method == "GET":
        # 获取所有的文章
        article = Article.query.get(pk)
        article_dict = article.to_dict()
        for comment in article_dict["comments"]:
            # 获得评论对象
            comment_obj = Comment.query.get(comment.get("id"))
            comment["username"] = comment_obj.user.username
        return render_template('article/show_article.html',article=article_dict)

    elif request.method == "POST":
        data = request.data.decode()
        # 转为字典数据
        data_dict = json.loads(data)
        if data_dict.get("user_id") == "":
            return jsonify("您还没有登录,请先登录后再评论")
        content = data_dict.get("data")
        user_id = data_dict.get("user_id")
        article_id = data_dict.get("article_id")
        # 判断是否为空
        if content == "":
            warn = "请输入文字再提交！"
            return jsonify(warn)
        else:
            comment = Comment(content=content,user_id=user_id,article_id=article_id)
            db.session.add(comment)
            db.session.commit()
            return jsonify("发表成功")

user/views.py
import os
from flask import Blueprint,request,render_template,flash,redirect,url_for
from flask import session,g
from werkzeug.security import generate_password_hash,check_password_hash
from user.form import LoginForm,RegisterForm
from user.models import db
from user.models import User
from common_function import random_Name,after_login

user = Blueprint("user",__name__)

@user.route('/login/',methods=["GET","POST"])
def login():
    if request.method == "GET":
        form = LoginForm()
        return render_template('user/login.html', form=form)

    else:
        form = LoginForm(formdata=request.form)
        # 验证是否符合表单校验
        if form.validate():
            password = form.password.data
            # 查找该用户
            user = User.query.filter_by(username=form.username.data).first()
            if check_password_hash(user.password,password) is False:
                flash("用户名或密码错误")
                return render_template('user/login.html',form=form)
            else:
                flash("登录成功")
                session['user'] = user.to_dict()
                return redirect(url_for("index"))
        else:
            # print(form.errors)
            return render_template('user/login.html', form=form)

@user.route('/register/',methods=["GET","POST"])
def register():
    if request.method == "GET":
        # data = jsonify("please register")
        # print(type(data))
        form = RegisterForm()
        return render_template('user/register.html',form=form)
    elif request.method == "POST":
        form = RegisterForm(formdata=request.form)
        # 判断是否验证成功
        if form.validate():
            isexist = User.query.filter_by(username=form.username.data).first()
            if isexist:
                flash(message="用户已存在")
                return redirect(url_for('user.register'))
            else:
                user = User(username=form.username.data,
                            password=generate_password_hash(form.password.data))
            # 将验证通过的用户保存至数据库
                db.session.add(user)
                db.session.commit()
                flash("注册成功,赶紧登录吧")
                return redirect(url_for('user.login'))
        else:
            # 消息闪现，是一个列表
            flash("注册失败")
            return render_template('user/register.html',form=form)



@user.route("/uploads/icon/",methods=["GET","POST"])
@after_login
def uploads():
    if request.method == "GET":
        return render_template('user/uploads.html')
    elif request.method == "POST":
        if session.get("user"):
            img_url = None
            # 获取上传的图片
            icon = request.files.get("icon")
            if icon:
                suffix = os.path.splitext(icon.filename)[-1]
                # 新名字
                newName = random_Name(suffix)
                from myblog.index import photo
                photo.save(icon,name=newName)
                img_url = photo.url(newName)
                # 获得用户对象保存头像url
                user = User.query.get(session["user"]["id"])
                user.icon = img_url
                db.session.commit()
                # 提示上传成功
                flash("上传成功")
                # 调用并执行上下文函数
                user_info()
                return redirect(url_for("index"))
            else:
                error = "您还没有选择图片，选择之后再上传"
                return render_template('user/uploads.html',error=error)
        else:
            # 未登录跳转到登录页面
            return redirect(url_for("user.login"))

# 应用上下文对象
@user.app_context_processor
def user_info():
    if session.get("user"):
        username = session["user"]["username"]
        # 重新刷新返回的字典对象
        user = User.query.filter_by(username=username).first()
        user_dict = user.to_dict()
        session["user"] = user_dict
        return session.get("user")
    else:
        return {}

@user.route("/logout/")
@after_login
def logout():
    session.pop("user")
    return redirect(url_for("index"))

templates/article/show_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ article.content[:8] }}</title>
    <script type="text/javascript" src="{{ url_for('static',filename='js/jquery-1.11.1.js') }}"></script>
</head>
<body>
<h3>{{ article.title }}</h3>
<br/><br/>
&nbsp;&nbsp;<p>{{ article.content }}</p>
<div class="comment">
    <h3>评论区</h3>
    <table>
        {% for comment in article.comments %}
        <tr>
            <td>{{ comment.username }}</td>
            <td width="200px">
            <td>{{ comment.content }}</td>
        </tr>
        {% endfor %}
    </table>
    <br/>
    <hr/>
    <h4>我的评论</h4>
        <textarea id="comment" style="width: 700px;height: 200px"></textarea>
        <br/>
        <button id="confirm" style="color: blue;">提交</button>
</div>
</body>
<script>
    $("#confirm").click(function () {
        var id = {{ article.id }} + "";
        var data = $("#comment").val();
        {% if id %}
            var user_id = {{ id }};
        {% else %}
            var user_id = "";
        {% endif %}
        var article_id = {{ article.id }}
        $.ajax({
            type: "POST",
            url: "http://127.0.0.1:5000/article/" + id + "/",
            data: JSON.stringify({"data":data,
                "user_id":user_id,
                "article_id":article_id}),
            contentType: "application/json; charset=utf-8",
            success: function (resp) {
                alert(resp);
            }
        });
    })
</script>
</html>

templates/article/write.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>写文章</title>
    <script type="text/javascript" src="{{ url_for('static',filename='js/jquery-1.11.1.js') }}"></script>
    <style>
        #qianyan{
            color: #843534;
            text-shadow: yellow;
            text-decoration: underline;
        }
    </style>
</head>
<body>
<h3 id="qianyan">在这里尽情分享你的故事，我愿意倾听！</h3>
<div id="head"></div>
<div id="body">
    <label>标题：</label>
    <textarea id="title" style="width: 700px;height: 30px"></textarea>
    <br/><br/>
    <label>正文：</label>
    <textarea id="content" style="width: 700px;height: 500px;"></textarea>
    <br/>
    <button id="appear" style="width: 50px;height: 25px;background-color: white">发表</button>
</div>
<div id="foot"></div>
</body>
<script>
    $("#appear").click(function (obj) {
        var title = $("#title").val();
        var content = $("#content").val();
        {% if id %}
            var user_id = {{ id }};
        {% else %}
            var user_id = "";
        {% endif %}
        $.ajax({
            type : "post",
            url : "http://127.0.0.1:5000/article/write/" ,
            data : JSON.stringify({"user_id":user_id,
                    "title":title,
                    "content":content}),
            dataType : "json",
            contentType : "application/json;charset=utf-8",
            success : function (data) {
                alert(data);
            }
        })
    })
</script>
</html>

templates/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>

    <title>YJWde博客</title>
    <!-- BOOTSTRAP CORE STYLE -->
    <link href="/static/css/bootstrap.css" rel="stylesheet"/>
    <!-- FONT AWESOME ICON STYLE -->
    <link href="/static/css/font-awesome.css" rel="stylesheet"/>
    <!-- CUSTOM STYLE CSS -->
    <link href="/static/css/style.css" rel="stylesheet"/>
    <style>
        .log {
            width: 300px;
        }
        .sign{
            font-size: 30px;
        }
        #user>ul{
            list-style: none;
            display: none;
        }
        #user:hover .log>ul{
            display: block;
        }
        #user .info{
            list-style: none;
            font-size: 12px;
        }
    </style>
</head>
<body>
<div id="header">
    <div class="overlay">
        <div class="container">
            <div class="row">
                <div class="col-md-4 logo-div">
                    <div class="logo-inner text-center">
                        <div class="logo-name">
                            <a href="index.html">
                                {% if icon %}
                                <img src="{{ icon }}" class="img-circle"/>
                                {% else %}
                                 <img src="/static/img/default.jpeg" class="img-circle"/>
                                {% endif %}
                            </a>
                            <div class="log">
                                {% if username %}
                                    <a style="font-size: 20px; color: #737373">Hello!</a>
                                    <a id="user" href="#">
                                        {{ username}}
                                    <ul>
                                        <li><a class="info">编辑信息</a></li>
                                        <li><a class="info" href="{{ url_for('user.uploads') }}">上传头像</a></li>
                                        <li><a class="info">修改密码</a></li>
                                        <li><a class="info" href="{{ url_for('user.logout') }}">登出</a></li>
                                    </ul>
                                    </a>
                                {% else %}
                                <a class="sign" href="{{ url_for('user.login') }}">登录</a>
                                {% endif %}|
                                <a class="sign" href="{{ url_for('user.register') }}">注册</a>
                            </div>
                        </div>

                    </div>

                </div>
                <div class="col-md-8 header-text-top " id="about">


                    <h1>分享我的程序人生.</h1>
                    我学习编程是建立在我想获得更好的物质生活，但现在我发现，其实敲代码也是一件很有意义的事情. <br/>
                    Here you can write a general notes about your blog.<br/>
                    <h2><strong>Who I am ? </strong></h2>
                    <i>I am YJW </i>

                </div>
            </div>
        </div>
    </div>
</div>
<!--END HEADER SECTION-->
<div class="info-sec">
    <div class="container">
        <div class="row">
            <div class="col-md-10">
                Say hello to me at <strong>Year</strong>&nbsp;life be better when your heart have changed
            </div>
            <div class="col-md-2">
                <div class="social-link">
                    <a href="https://blog.csdn.net/yangjianwei0309" target="_blank" class="btn btn-default btn-xs">
                        <img src="/static/img/csdn.jpg"></a>
                    <a href="https://github.com/yangjianwei0309" target="_blank" class="btn btn-default btn-xs">
                        <img src="/static/img/github.jpg"></a>
                    <a href="http://www.bootcss.com/" target="_blank" class="btn btn-default btn-xs">
                        <img src="/static/img/bootstrap.jpg"></a>
                </div>

            </div>

        </div>
    </div>
</div>
<!--END INFO SECTION-->
<div class="container">

    <div class="row">

        <div class="col-md-8 ">
            {% for article in articles %}
            <div class="blog-post">
                <h2>{{ article.title }}</h2>
                <h4>作者： <a href="#">{{ article.user }}</a> 时间：2018.8.8 </h4>
                <p>
                    {{ article.content[:50] }}
                </p>
                <a href="/article/{{ article.id }}/" class="btn btn-default btn-lg ">
                    查看更多<i class="fa fa-angle-right"></i></a>
            </div>
            {% endfor %}

            <br/>
            <nav>
                <ul class="pagination">
                    <li>
                        <a href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">5</a></li>
                    <li>
                        <a href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-3" style="padding-top: 30px;">
            <div class="row">
                <ul class="list-group">
                    <li class="list-group-item"><strong>CATEGORIES</strong></li>
                    <li class="list-group-item"><a href="{{ url_for('article.write') }}">写文章</a></li>
                    <li class="list-group-item">Morbi leo risus</li>
                    <li class="list-group-item">Porta ac consectetur ac</li>
                    <li class="list-group-item">Vestibulum at eros</li>
                    <li class="list-group-item">Dapibus ac facilisis in</li>
                    <li class="list-group-item">Morbi leo risus</li>
                    <li class="list-group-item">Porta ac consectetur ac</li>
                    <li class="list-group-item">Vestibulum at eros</li>
                </ul>
            </div>
            <div class="row">
                <h3>Advertising</h3>


            </div>
        </div>

    </div>


</div>

<!--END HOME PAGE SECTION-->
<div class="footer-sec" style="margin-top: 0px;">
    <div class="container">
        <div class="row">
            <div class="col-md-12 foo-inner">
            </div>
        </div>
    </div>
</div>
<!-- END FOOTER SECTION -->
<!-- JAVASCRIPT FILES PLACED AT THE BOTTOM TO REDUCE THE LOADING TIME -->
<!-- CORE JQUERY -->
<script src="/static/js/jquery-1.11.1.js" type="text/javascript"></script>
<!-- BOOTSTRAP SCRIPTS -->
<script src="/static/js/bootstrap.js" type="text/javascript"></script>

</body>
</html>

templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户登录</title>
</head>
<body>
<form action="{{ url_for('user.login') }}" method="post">
    <!--<input type="text" name="username">-->
    <p>{{form.username.label}} {{form.username}}
        <span style="color:red;">{{form.username.errors[0] }}</span>
    </p>

    <!--<input type="password" name="pwd">-->
    <p>{{form.password.label}} {{form.password}}
        <span style="color: red;">{{form.password.errors[0] }}</span>
    </p>
    {% set msgs = get_flashed_messages() %}
    {% if msgs %}
        <p style="color: red;">{{ msgs[0] }}</p>
    {% endif %}
    <input type="submit" value="提交">
    {{ form.csrf_token }}
</form>
</body>
</html>

templates/user/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户注册</title>
</head>
<body>
<form action="{{ url_for('user.register') }}" method="post">
    <p>{{ form.username.label }} {{ form.username }}
        <span style="color: red;">{{ form.username.errors[0] }}</span>
    </p>
{#    {% for message in get_flashed_messages() %}#}
{#        <span>{{ message }}</span>#}
{#    {% endfor %}#}
    <p>{{ form.password.label }} {{ form.password }}
        <span style="color: red">{{ form.password.errors[0] }}</span>
    </p>
{#    {% for message in get_flashed_messages() %}#}
{#        <span>{{ message }}</span>#}
{#    {% endfor %}#}
    <p>{{ form.password2.label }} {{ form.password2 }}
        <span style="color: red;">{{ form.password2.errors[0] }}</span>
    </p>
{#    {% for message in get_flashed_messages() %}#}
{#        <span>{{ message }}</span>#}
{#    {% endfor %}#}
    <input type="submit" value="注册">
    {% if get_flashed_messages() %}
    {% set msgs = get_flashed_messages() %}
    {% for msg in msgs %}
        <p style="color: blue;">{{ msg }}</p>
    {% endfor %}
    {% endif %}
    {{ form.csrf_token }}
</form>
</body>
</html>

templates/user/uploads.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>上传头像</title>
</head>
<body>
<form action="{{ url_for('user.uploads') }}" method="post" enctype="multipart/form-data">
    <input type="file" name="icon">
    <input type="submit" value="上传">
    {% set msgs = get_flashed_messages() %}
    {% for msg in msgs %}
        <span style="color: darkorange;"{{ msg }}></span>
    {% endfor %}
    {% if error %}
    <span style="color:red;" >{{ error }}</span>
    {% endif %}
</form>
</body>
</html>